python-restx/flask-restx

- doc/mask.rst
- doc/swagger.rst
- flask_restx/api.py
- flask_restx/marshalling.py
- flask_restx/representations.py
- flask_restx/resource.py
- flask_restx/swagger.py
- tests/conftest.py
- tests/legacy/test_api_legacy.py
- tests/test_fields_mask.py
- tests/test_payload.py
Addresses https://github.com/python-restx/flask-restx/issues/8
Flask configuration variables were missed (my fault) in https://github.com/python-restx/flask-restx/pull/2. This PR renames these and should *hopefully* be the last of the renaming required (therefore closing https://github.com/python-restx/flask-restx/issues/1) !
> Rename config variables: RESTPLUS_* -> RESTX_*

- .travis.yml
- CONTRIBUTING.rst
- bumpr.rc
- flask_restx/__about__.py
addresses #6 
Added a token in travis-ci to allow to push releases on PyPi.
I'll need to push a tag in order to test everything is working as expected.
> allow travis to push releases on PyPi

- flask_restx/swagger.py
The new(ish) Wildcard field does not get registered in the docs because it isn't checked for when registering fields. This PR is a monkeypatch I have been using, but I think it is the correct behaviour.
> register nested model wildcard fields in docs

- requirements/install.pip
This is a hotfix for #34 until we have a proper fix.
> fix: enforce werkzeug <= 0.16.1 until we get a proper fix

- CONTRIBUTING.rst
- bumpr.rc
- flask_restx/__about__.py
Document the release process through `bumpr`.
> Setup bumpr

- .github/workflows/test.yml
- .travis.yml
Skipping the Coveralls step if action is run in a fork repo in the GitHub Actions
Using Travis to run the coveralls for PRs
Example: https://github.com/SVilgelm/flask-restx/runs/433679573?check_suite_focus=true
It's temporary solution until the https://github.com/codecov/codecov-action/issues/29 is resolved
> Run coveralls using travis for PRs

- flask_restx/api.py
- flask_restx/marshalling.py
- flask_restx/mask.py
- flask_restx/model.py
- flask_restx/swagger.py
- flask_restx/utils.py
- tests/test_fields.py
- tests/test_fields_mask.py
- tests/test_marshalling.py
- tests/test_model.py
in `flask_restx/model.py` and `flask_restx/swagger.py` logic is installed to
circumvent differences in Python2 and Python3 when importing from the
collections module. Some classes from collections has been moved to
`collections.abc` in Python3. `OrderedDict` is not one of them, hence an
ImportError is raised when trying to import `OrderedDict` from
collections.abc. This then leads to importing both `OrderedDict` AND
`MutableMapping`/`Hashable` from `collections.abc` which then raises a
`DeprecationWarning` since `MutableMapping`/`Hashable` lives in
`collections.abc` in Python3.
This patch should fix those `DeprecationWarning`s to be raised.
Output from running `pytest` in a project that uses flask_restx. Here the `DeprecationWarning`s are seen clearly. I've only fixed the ones pertaining …
> Avoid DeprecationWarning when importing OrderedDict

- flask_restx/api.py
- requirements/install.pip
- requirements/test.pip
- tests/test_errors.py
Fixes: #34
This import breaks with werkzeug 1.0. 
Before 1.0, werkzeug was generating this warning: 
> DeprecationWarning: The import 'werkzeug.cached_property' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.utils import cached_property' instead.
> Remove deprecated werkzeug import

- .github/workflows/test.yml
- requirements/test.pip
- setup.cfg
Use [ossaudit](https://github.com/illikainen/ossaudit) to audit the installed packages.
The ossaudit supports python versions >= 3.5, so the workflow skips the audition for py27 and pypy2.
Partially implements #29
> Audit Python packages for known vulnerabilities

- requirements/test.pip
The pytest-sugar and pytest-5.0.1 are broken for python 3.8. 
Removing pytest-sugar and updating pytest solves the problem and unblocks the CI.
> Remove pytest-sugar from requirements and update pytest

- .github/workflows/test.yml
- .travis.yml
> Use Codecov instead of coveralls

- .github/workflows/release.yml
Updating flask-restx-feedstock repo with new version by creating a pull request when a new release is published.
Close #28 
Tested on my fork: https://github.com/SVilgelm/flask-restx/runs/433937063?check_suite_focus=true
Here is PR for the version 0.1.1 created by release action: https://github.com/conda-forge/flask-restx-feedstock/pull/7
> Update feedstock on release

- flask_restx/api.py
- flask_restx/swagger.py
- tests/test_swagger.py
Changes:
- Added a `RESTX_INCLUDE_ALL_MODELS` config option with a `False` default value.
- `Swagger.as_dict()` now adds all existing models to the documentation if `RESTX_INCLUDE_ALL_MODELS` is set.
- Added tests for `RESTX_INCLUDE_ALL_MODELS`.
> Make it possible to include "unused" models in the generated swagger documentation, refs #90

- examples/complex.py
- examples/todo.py
- examples/todomvc.py
Below error is occurring while running the sample TODO App. 
```
Traceback (most recent call last):
File "app.py", line 3, in <module>
from werkzeug.contrib.fixers import ProxyFix
ModuleNotFoundError: No module named 'werkzeug.contrib'
```
Root cause for this issue is `ProxyFix` has been moved from werkzeug.contrib.fixers  to `werkzeug.middleware.proxy_fix.ProxyFix` 
More details can be found at https://werkzeug.palletsprojects.com/en/1.0.x/middleware/proxy_fix/?highlight=proxyfix#werkzeug.middleware.proxy_fix.ProxyFix
> ProxyFix import issue has been fixed.

- doc/index.rst
- doc/quickstart.rst
- add a HOWTO easily migrate from Flask-RESPlus (ref #99)
- explain about the fork in the doc
> Documentation improvements

- doc/swagger.rst
This example has 2 main issues:
1. The model assigned to the fields variable shadows the flask_restx.fields
module, causing an AttributeError
2. The @api.model usage is simply incorrect, it is not intended to be
used as a class decorator on custom field implementations.
The corrections made here show what I *assume* the original author intended to show.
https://github.com/python-restx/flask-restx/issues/117#issuecomment-625756628
> [docs] Fix incorrect input/output model examples.

- flask_restx/fields.py
- tests/test_fields.py
When marshalling receiving a `MarshallingError` is much more useful than
receiving the underlying exception directly as the `MarshallingError`
has context about where it happened and it means all marshalling issues
can be handled in one place.
This change also catches `TypeError`s from the int and float formatters
so that they are correctly turned into `MarshallingError`s.
See: #75
> Fix Issue #75: Catch TypeError in marshalling

- doc/parsing.rst
In the File Upload section of the documentation, the link to the Flask documentation section was broken/outdated. Changed it from https://flask.palletsprojects.com/en/0.10.x/patterns/fileuploads/ to https://flask.palletsprojects.com/en/1.1.x/patterns/fileuploads/
> Update the Flask documentation URL in the File Upload section

- flask_restx/swagger.py
- tests/test_swagger.py
This is a port of https://github.com/noirbizarre/flask-restplus/pull/656
It should resolve #110 
Thanks to @buggyspace, @drarok and @edwardfung123 for identifying and fixing this.
I've followed the CONTRIBUTING.rst file, but couldn't locate the changelog to add this change, is this out of date?
> Add support for recursive models

- flask_restx/fields.py
- tests/test_fields.py
Currently with a Boolean field it isn't possible to set the example to
'False' since it would instead be set to None.
Fixes #206
> Allow example=False

- flask_restx/api.py
This resolves any issues with mixed content when running behind an HTTPS reverse proxy.
There is no valid use case for using absolute over relative here, and only causes additional issues.
Resolves #188
> Use relative path for `api.specs_url`.

- flask_restx/model.py
- flask_restx/namespace.py
- tests/test_namespace.py
This PR adds optional strict validation to @api.expect
Issue #186
> issue#186 - allow strict mode when validating model fields

- doc/quickstart.rst
- flask_restx/api.py
- tests/test_errors.py
rename ERROR_404_HELP -> RESTX_ERROR_404_HELP (fixes #114)
> add prefix to config setting

- flask_restx/api.py
- flask_restx/namespace.py
Using an regular dict on error_handlers, both at Api and at Namespace, mean that which handler was not predictable. We had 2 error handlers, one for a generic service exception and one for a more specific exception that needed special care. Our registration worked some times, but not others, and this is the root cause. Here is a sample of what we had
```
class GenericError(Exception):
pass
class SomeSpecificError(Exception):
pass
ns = Namespace("some_route")
@ns.errorhandler(SomeSpecificError)
def handle_specific_error(error):
return {"message": "something specific happened"}, 401
@ns.errorhandler(GenericError)
def handle_specific_error(error):
return {"message": "generic error"}, 401
```
and a route was raising `SomeSpecificError`. One sees ocurrences of one or the other message …
> Make error handlers order of registration respected when handling errors

- README.rst
Correct spelling for read only properties is 'readonly'
> bug fix typo in README.rst

- requirements/install.pip
aniso8601==8.1.0 * raises ValuError in case of non-string arguments
passed to get_date_resolution and parse_date methods.
It is ok for Python3 envs, but backward incompatible for Python 2.7
where we are passing unicode (at least in unittests).
* https://bitbucket.org/nielsenb/aniso8601/src/master/CHANGELOG.rst
> Cap aniso8601 for python 2.7 environments

- flask_restx/fields.py
- tests/test_fields.py
This PR fixes https://github.com/python-restx/flask-restx/issues/91.
> fix: Unable to access nested list property

- flask_restx/swagger.py
When setting `ordered=True` in a Namespace, nested models are not registered with `Swagger` giving a "Could not resolve reference" in Swagger documentation. This pull request fixes this.
Related bug reports and pull requests:
- https://stackoverflow.com/questions/56079764/flask-restplus-nested-fields-not-getting-registered-into-swaggerui
- https://github.com/noirbizarre/flask-restplus/issues/643
- https://github.com/noirbizarre/flask-restplus/pull/616/commits/847664e1b144a3da82e243b8fdf11b7677382e71
- https://github.com/python-restx/flask-restx/issues/128
> Fixing unregistered nested ordered model bug

- doc/scaling.rst
The example for `Multiple APIs with reusable namespaces` is incomplete and using variables that clash with previous examples on the same page.
This PR aims to provide a complete example by providing an example of a blueprint that can be used by the established documentation.
> improve scaling example

- flask_restx/api.py
- tests/test_errors.py
Fixes issue https://github.com/python-restx/flask-restx/issues/285.
When an `errorhandler` is registered on a namespace, and `PROPAGATE_EXCEPTIONS` is set to `True` in the Flask app, then the namespace handler will not catch the exceptions. It looks like this is due to the `handle_error` function not checking the error handlers that exist in any child classes.
> Fix namespace error handlers when propagate_exceptions=True

- doc/marshalling.rst
This commit fixes a typo in the first sentence of the first paragraph of "Response marshalling".
> Fix typo in docs, in the marshalling.rst intro

- examples/resource_class_kwargs
This Example shows how to inject the logic to a given communication layer.
This allows to have the specification separated from the business logic
> add example with loosly coupled implementation

- requirements/install.pip
Flask and werkzeug recently hit 2.0.0 milestones. This caused some
breaking changes related to flask-restx. Until some upstream bugs are
fixed, and we're able to identify all breaking changes, pin to < 2.0.0
versions
> pyenPin flask and werkzeug

- flask_restx/api.py
Changed in: https://github.com/pallets/flask/commit/b146a13f633b0e2e26e3b8383b3db0feb563bc83
Fixes: #308
Signed-off-by: Jürgen Löhel <juergen.loehel@inlyse.com>
> The Flask/Blueprint API moved to the Scaffold base class

- package.json
> Upgrade swagger ui to 3.48.0

- package.json
This is the error message I got when I ran `inv assets`:
npm WARN Invalid version: "0.4.1.dev"
npm WARN flask-restx No description
npm WARN flask-restx No repository field.
npm WARN flask-restx No README data
npm WARN flask-restx No license field.
> No ".dev" should appear in package.json version number

- flask_restx/fields.py
- flask_restx/marshalling.py
- tests/test_marshalling.py
This resolves issue #304. The `ordered` parameter was not being passed along to `output()` in one case. It is now passed, and items are popped from the front to retain the original order. Original behavior is kept in case someone needs/wants it.
Test case also added to check ordered vs. not ordered.
> Issue #304: pass along ordered parameter

- flask_restx/fields.py
- tests/test_fields.py
This resolves issue #240 and provides a test to cover the case. Picks up from where PR #277 stalled. 
.venv is also added to the .gitignore (created by [virtual-fish](https://github.com/justinmayer/virtualfish)--let me know if you'd like it removed!
> Issue #240: use default on None Float field

- flask_restx/api.py
- flask_restx/resource.py
- requirements/install.pip
This code imports `BaseResponse` if version of `werkzeug` is less than 2.0.0 otherwise it imports `Response` as suggested.
In addition to that, it forbids `werkzeug` and `flask` version `2.0.0` because description of `HttpException` becomes `None` and it fails the tests. This behavior is fixed in version `2.0.1`, so users still can use version `2.0.1`. @j5awry I know changes are short but could you take a look at it? Or, is the repo waiting for more people to report breaking changes? In that case, could you let us know when that period will end?
> #313 don't use werkzeug, flask 2.0.0 and use Response instead of BaseResponse

- .editorconfig
- CONTRIBUTING.rst
- README.rst
- doc/Makefile
- doc/conf.py
- doc/errors.rst
- doc/example.rst
- doc/make.bat
- doc/parsing.rst
- doc/quickstart.rst
- doc/scaling.rst
- doc/swagger.rst
- flask_restx/cors.py
- flask_restx/swagger.py
- setup.py
I fixed a bunch of documentation link problems.
Flask's doc is now hosted at https://flask.palletsprojects.com/ and its documentation was updated, rendering multiple intersphinx mappings broken.
Many other URLs in docs were using http instead of https and some links were broken or didn't lead to where they should have.
The quickstart section to migrate from restplus to restx didn't render the two bash commands in code blocks.
PyInvoke's link in CONTRIBUTING was using the markdown syntax instead of RST and was broken.
I tested all the suggested changes :slightly_smiling_face: 
:man_juggling: :snake:
> Update broken/outdated documentation links

- flask_restx/api.py
- tests/test_errors.py
Cherry-picked the changes by @chandlernine from #294 and added a test in test_errors.py as advised.
> Do not call got_request_exception for exceptions explicitly handled

- CHANGELOG.rst
Added all contributions to the changelog.rst
> prep-0.5.0 Changelog

- flask_restx/api.py
- tests/test_swagger.py
This PR suggests a fix for issue #191:
*  Add default_swagger_filename parameter to restx's api.py instead of hardcoding it.
> Add default swagger filename to Api.

- flask_restx/reqparse.py
- tests/test_reqparse.py
Fixes #422 
pallets/werkzeug#2339 changed the behavior of Request.get_json()
and the Request.json property to raise a BadRequest if Request.json
is accessed and the content type is not `application/json`.
Argument parsing allows parsing from multiple locations, but if the
locations include `json` and the content type is not `application/json`,
a `BadRequest` is now raised with Werkzeug >= 2.1.0.
Handle this case and continue argument parsing.
> Handle change to Werkzeug 2.1.0 change to Request.get_json().

- flask_restx/swagger.py
This is an attempt to fix issue #460, where werkzeug used to expose a function `werkzeug.routing.parse_rule` but made it private as of werkzeug==2.2.0.
The method was extracted from [this change](https://github.com/pallets/werkzeug/commit/5a7c0dec029d296a5e8131c8db51ce19e28c0c58#diff-f353ec8ecb0bad3d3c6527734c587a80fc81c8cc4a8002b13242a06c8c9f6dddL83-L112) which seems to be when it was fully removed from werkzeug.
Copying it into this project because the method is self-contained. One alternative would be to pin the werkzeug version, which isn't a terrible idea, but also means this project would miss out on future werkzeug improvements. 🤷 Neither option is great but copy-paste is simple so that's what I did.
* ❌ Right now the `ossaudit` check is failing, which prevents the other checks …
> Fix #460 - missing parse_rule method

- .github/workflows/test.yml
ossaudit has lots of flase positives. And there's better ways to address security for depenencies within github.
What types of changes does your code introduce?
- [x ] Bugfix (non-breaking change which fixes an issue)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
- [x ] I have read the [guidelines for contributing](https://github.com/python-restx/flask-restx/blob/master/CONTRIBUTING.rst)
- [x ] All unit tests pass on my local version with my changes
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …
> remove ossaudit 

- .github/workflows/black.yml
- .github/workflows/test.yml
- CHANGELOG.rst
- README.rst
- tox.ini
Fix failing pypy install on github actions after `ubuntu:latest` was updated to be Ubuntu 22.04. 
This needs to be merged before https://github.com/python-restx/flask-restx/pull/500 as the checks don't currently pass.
> Fix actions tidy up tox

- flask_restx/api.py
Flask 2.2.0 issues a warning if a url rule is added to a blueprint after it has been registered, so this commit ensures that the documentation rules are added before the blueprint is registered.
Fixes: #485
> Fix UserWarning on Flask 2.2.0

- CHANGELOG.rst
- flask_restx/api.py
Update changelog to include fixes for Flask 2.3 compatibility and prepare for release.
> Update changelog and prepare for release.

- CHANGELOG.rst
- flask_restx/api.py
- tests/test_errors.py
Fixes #512 which accidentally changed the exception propagation behaviour.
> Fixes behaviour change bug #512

- flask_restx/api.py
Despite my fix, some testing showed it was still incorrect because the user couldn't override app.testing or app.debug if they didn't want to propagate exceptions. This simply copies the flask implementation as is instead.
> One further changes to fix propagate exceptions.

- .github/workflows/test.yml
- CHANGELOG.rst
- requirements/test.pip
- setup.py
- tox.ini
This PR adds Python 3.11 suppport. No code changes required, just updates to the github actions and test framework.
> Add python 3 11 support

- CHANGELOG.rst
- README.rst
- doc/scaling.rst
- package.json
This PR updates Swagger UI to address some outstanding CVEs flagged by dependabot.
> Updates to address swagger CVEs.

- CHANGELOG.rst
- doc/quickstart.rst
- package.json
Add a note to the quick-start docs about registering the `/` route since it seems to come up on issues quiet often.
> Update docs root route

- CHANGELOG.rst
- tests/legacy/test_api_legacy.py
Change in Werkzeug 2.3.5 as [issued here](https://github.com/pallets/werkzeug/issues/2716) caused the fail in build. As per [HTTP RFC](https://www.rfc-editor.org/rfc/rfc9110#section-12.5.1) the quality-factor for HTTP Accept Header has to be like `X.X`. So changing them all to such format, all Unit tests and Tox test passes.
Fixes #547
> issue-547 http header quality factor number

- doc/marshalling.rst
This commit fixes a typo in the `Wildcard` section in Response marshalling
> Fix typo in doc/marshalling.rst

- .github/workflows/test.yml
- CHANGELOG.rst
- README.rst
- doc/index.rst
- doc/installation.rst
- setup.py
- tox.ini
As discussed in #553 Python 3.7 is EOL and can be dropped. 
I saw one remark considering old python versions that need some attention I guess but can be addressed in a different PR. 
https://github.com/python-restx/flask-restx/blob/b1e5d192261abbae91a67b1cfb29f16d53540ec3/setup.cfg#L15C4-L19
> Drop support for python 3.7

- flask_restx/schemas/__init__.py
- requirements/install.pip
In preparation to support Python 3.12 pkg_resources need to be removed. 
According to there migration guide it can be replaced by `importlib_resources`
https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename
> Replace pkg_resources with importlib_resources

- CHANGELOG.rst
- README.rst
- requirements/install.pip
- requirements/test.pip
This PR introduces a temporary restriction on flask, werkzeug and jsonschema packages until we can get everything updated. 
It was my intention to temporarily point the pytest-flask installation to a fork that included the 3.0.0 fixes until they are merged upstream. However, the pipeline installs via setuptools and the `pip()` function in `setup.py` strips out pip git checkout links.
> Introduce temporary package version restrictions

- CHANGELOG.rst
- flask_restx/api.py
- flask_restx/resource.py
- flask_restx/utils.py
- tests/test_utils.py
Fix for removed `wekzeug.__version__` #573 and  Logical follow up to replacement of pkg_resources replacement  #562 . 
**_Design decision_**: I decided to create separate import function `import_werkzeug_response` to do not mess up with global import space with `import werkzeug` in case of future version conflicts.  `BaseResponse` is now imported once within `flask_restx.utils` module internally with method `import_werkzeug_response` and  accessible as `flask_restx.utils.BaseResponse` .
> fix: BaseResponse import - replace wekzeug import  __version__ by importlib (#573)

- .github/workflows/test.yml
- tox.ini
To get more insight if our fixes are working for both flask version I created a test-matrix for flask 2 (<3.0.0) & flask 3 (>=3.0.0)
> Add flask 2 (<3.0) and flask 3 (>=3.0) to test matrix and do not fast fail

- CHANGELOG.rst
- flask_restx/api.py
- tests/test_errors.py
Fixes https://github.com/python-restx/flask-restx/issues/569.
All details are in the issue.
The code fixes both of the issues:
Feel free to edit the PR to match your expectations ☺️
> Fix wrong status code and message on responses when handling `HTTPException`s

- CHANGELOG.rst
- README.rst
- doc/swagger.rst
- flask_restx/api.py
- flask_restx/utils.py
- package.json
- requirements/install.pip
- requirements/test.pip
- setup.py
This PR provides the final updates to enable Flask >= 3.0.0 support.
> Prepare release 1.3.0
